#include "test_pwm.h"

void test_hal_pwm_setup_configures_timer_correctly(void) {
    hal_pwm_setup(1000, 0.5f); 
    TEST_ASSERT_EQUAL_UINT32(83999, TIM2->ARR);
    TEST_ASSERT_UINT32_WITHIN(5, 42000, TIM2->CCR1);
    TEST_ASSERT_BITS_HIGH(TIM_CR1_CEN, TIM2->CR1);
    TEST_ASSERT_BITS_HIGH(TIM_CCMR1_OC1PE, TIM2->CCMR1);
    TEST_ASSERT_BITS(TIM_CCMR1_OC1M, (6 << 4), TIM2->CCMR1);
    TEST_ASSERT_BITS_HIGH(TIM_CCER_CC1E, TIM2->CCER);
}